name: Tests
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 10.x
          - 12.x
          - 14.x
          - 16.x
          - 18.x
          - 20.x
        jest:
          - ./jest/24
          - ./jest/25
          - ./jest/26
          - ./jest/27
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Pack jest-runner-grouped-tests
        run: npm pack
      - name: Debug - List files after packing
        run: ls -l
      - name: Install test dependencies
        working-directory: ${{ matrix.jest }}
        run: npm i
      - name: Debug - Output Jest configuration
        working-directory: ${{ matrix.jest }}
        run: npx jest --showConfig
      - name: Add jest-runner-grouped-tests
        working-directory: ${{ matrix.jest }}
        run: npm i "../../jest-runner-grouped-tests-`cat ../../package.json | jq .version -r`.tgz"
      - name: Run tests
        working-directory: ${{ matrix.jest }}
        run: |
          node --version
          npx jest --version
          npm test
